Document: phantomjs
Title: Debian phantomjs Manual
Author: <insert document author here>
Abstract: This manual describes what phantomjs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/phantomjs/phantomjs.sgml.gz

Format: postscript
Files: /usr/share/doc/phantomjs/phantomjs.ps.gz

Format: text
Files: /usr/share/doc/phantomjs/phantomjs.text.gz

Format: HTML
Index: /usr/share/doc/phantomjs/html/index.html
Files: /usr/share/doc/phantomjs/html/*.html
